package com.jin.simple;

global org.slf4j.Logger logger;
import java.lang.Number;
import java.lang.Integer;
import com.jin.domain.Athlete;
import com.jin.domain.Team;

rule AssignTeam
	//dialect "mvel"
	when
		_althlete : Athlete(age < 10)
		_team : Team(level == "peewee")
	then
		_team.addMember(_althlete);
		insert(_team);
		logger.info("Simple Rule applied!");
		logger.info("" + _althlete.getAge());
end
