package com.jin.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Athlete implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String firstName;
   private java.lang.String lastName;
   private java.lang.String gender;
   private java.lang.Integer age;

   public Athlete()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public Athlete(java.lang.String firstName, java.lang.String lastName,
         java.lang.String gender, java.lang.Integer age)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.gender = gender;
      this.age = age;
   }

}