package com.jin.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Team implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String name;
   private String sport;

   private List<Athlete> members;

   public Team()
   {
	   this.members = new ArrayList<Athlete>();
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSport()
   {
      return this.sport;
   }

   public void setSport(java.lang.String sport)
   {
      this.sport = sport;
   }

   public List<Athlete> getMembers()
   {
      return this.members;
   }

   public void setMembers(List<Athlete> members)
   {
      this.members = members;
   }

   public Team(String name, String sport,
         List<Athlete> members)
   {
      this.name = name;
      this.sport = sport;
      this.members = members;
   }
   
   public void addMember(Athlete athlete)
   {
       this.members.add(athlete);
   }

}