package com.jin.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Team implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String name;
   private String level;

   private List<Athlete> members;

   public Team()
   {
	   this.members = new ArrayList<Athlete>();
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getLevel()
   {
      return this.level;
   }

   public void setLevel(String level)
   {
      this.level = level;
   }

   public List<Athlete> getMembers()
   {
      return this.members;
   }

   public void setMembers(List<Athlete> members)
   {
      this.members = members;
   }

   public Team(String name, String level)
   {
      this.name = name;
      this.level = level;
    }
   
   public void addMember(Athlete athlete)
   {
       this.members.add(athlete);
   }

}